name: Compile game and build assets folder

on: 
    workflow_dispatch:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - run: sudo apt-get update
            - run: sudo apt-get install haxe -y
            - run: mkdir ~/haxelib && haxelib setup ~/haxelib
            - uses: actions/checkout@v4
              with:
                repository: FunkinCrew/Funkin
                submodules: recursive
            #ts so repetitive 💔
            #I dont really care  i dont know github actions and i dont want to
            - run: haxelib --global install hmm
              working-directory: ${{ github.workspace }}
            - run: haxelib --global run hmm setup
              working-directory: ${{ github.workspace }}
            - run: hmm install
              working-directory: ${{ github.workspace }}
              #it asks a question that you have to type y into to downkload
            - run: echo "y" | haxelib run lime setup
              working-directory: ${{ github.workspace }}
            - run: lime build html5
              working-directory: ${{ github.workspace }}
            - uses: actions/upload-artifact@v4
              with:
                path: ${{ github.workspace }}/export/release/html5/bin/assets
                if-no-files-found: error
                #might be problematic if this hasnt run in 30 days
                retention-days: 30
