name: Compile game and build assets folder

on: 
    workflow_dispatch:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - run: sudo apt-get update
            - run: sudo apt-get install haxe -y
            - run: mkdir ~/haxelib && haxelib setup ~/haxelib
            - uses: actions/checkout@v4
              with:
                repository: FunkinCrew/Funkin
                submodules: recursive
            #ts so repetitive 💔
            #I dont really care  i dont know github actions and i dont want to
            - run: haxelib --global install hmm
              working-directory: ${{ github.workspace }}
            - run: haxelib --global run hmm setup
              working-directory: ${{ github.workspace }}
            - run: hmm install
              working-directory: ${{ github.workspace }}
              #it asks a question that you have to type y into to downkload
            - run: echo "y" | haxelib run lime setup
              working-directory: ${{ github.workspace }}
            - run: lime test html5
              working-directory: ${{ github.workspace }}
            #no use in using any scripts cause theyre all in haxe
            - run: sudo rm rf export/release/html5/bin/assets/scripts
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                file_pattern: export/release/html5/bin/assets
